"""ParallelGeneration — generate content from multiple models simultaneously."""
from __future__ import annotations

import time
from typing import Any, Callable, Dict, List, Optional

from .models import ModelResponse


class ParallelGeneration:
    """Generate content from multiple models in parallel (simulated)."""

    def __init__(self, max_parallel: int = 5) -> None:
        self.max_parallel = max_parallel
        self._history: List[Dict[str, Any]] = []

    def generate(self, prompt: str, models: List[str],
                 call_fn: Optional[Callable[[str, str], ModelResponse]] = None,
                 **kwargs: Any) -> List[ModelResponse]:
        results: List[ModelResponse] = []
        start = time.time()

        for model in models[:self.max_parallel]:
            if call_fn:
                try:
                    r = call_fn(prompt, model)
                    results.append(r)
                except Exception as exc:
                    results.append(ModelResponse(model=model, provider="unknown",
                                                 content="", error=str(exc)))
            else:
                results.append(ModelResponse(
                    model=model, provider="simulated",
                    content=f"Generated by {model}: {prompt[:60]}",
                    confidence=0.75, latency_ms=120.0 + len(results) * 40,
                ))

        elapsed = (time.time() - start) * 1000
        self._history.append({"prompt": prompt[:100], "models_used": len(results),
                              "elapsed_ms": elapsed})
        return results

    def get_history(self) -> List[Dict[str, Any]]:
        return list(self._history)
