from layers.layer10_monetization.modules.amazon_product_intake import normalize_amazon_product


def test_normalize_amazon_product_extracts_asin_and_tag():
    result = normalize_amazon_product(
        product_name="Example Product",
        product_url="https://www.amazon.com/dp/B012345678",
        affiliate_link="https://www.amazon.com/dp/B012345678?tag=example-20",
        niche="beauty",
    )
    assert result.asin == "B012345678"
    assert result.tracking_id == "example-20"
    assert result.niche == "beauty"


def test_rejects_non_amazon_urls():
    try:
        normalize_amazon_product(
            product_name="Example Product",
            product_url="https://example.com/product/B012345678",
            affiliate_link="https://www.amazon.com/dp/B012345678?tag=example-20",
        )
    except ValueError as exc:
        assert "Amazon" in str(exc)
    else:
        raise AssertionError("expected ValueError")


def test_requires_affiliate_link():
    try:
        normalize_amazon_product(
            product_name="Example Product",
            product_url="https://www.amazon.com/dp/B012345678",
            affiliate_link="https://www.amazon.com/dp/B012345678",
        )
    except ValueError:
        pass
    else:
        # A plain Amazon URL is syntactically valid, but the intake contract
        # requires a link generated by an approved affiliate workflow.
        raise AssertionError("expected ValueError")
