"""Data models for Learning Connector."""
from __future__ import annotations
import time
import uuid
from enum import Enum
from typing import Any, Dict, List, Optional


class LearningEvent:
    """A single learning data point collected from a module."""
    __slots__ = ("event_id", "module", "event_type", "score", "metadata",
                 "success", "timestamp", "source")

    def __init__(self, module: str, event_type: str, score: float = 0.0,
                 metadata: Optional[Dict[str, Any]] = None,
                 success: bool = True, source: str = "") -> None:
        self.event_id: str = f"lev_{uuid.uuid4().hex[:8]}"
        self.module: str = module
        self.event_type: str = event_type
        self.score: float = score
        self.metadata: Dict[str, Any] = metadata or {}
        self.success: bool = success
        self.timestamp: float = time.time()
        self.source: str = source

    def to_dict(self) -> Dict[str, Any]:
        return {s: getattr(self, s) for s in self.__slots__}


class PerformanceMetric:
    """A performance metric for analysis."""
    __slots__ = ("metric_id", "name", "module", "value", "target",
                 "status", "trend", "timestamp")

    def __init__(self, name: str, module: str, value: float,
                 target: float = 0.0, trend: str = "stable") -> None:
        self.metric_id: str = f"pm_{uuid.uuid4().hex[:8]}"
        self.name: str = name
        self.module: str = module
        self.value: float = value
        self.target: float = target
        self.status: str = self._calc_status(value, target)
        self.trend: str = trend
        self.timestamp: float = time.time()

    @staticmethod
    def _calc_status(value: float, target: float) -> str:
        if target <= 0:
            return "unknown"
        ratio = value / target
        if ratio >= 1.0: return "excellent"
        if ratio >= 0.8: return "good"
        if ratio >= 0.5: return "needs_improvement"
        return "poor"

    def to_dict(self) -> Dict[str, Any]:
        return {s: getattr(self, s) for s in self.__slots__}


class MistakeRecord:
    """Record of a detected mistake or failure."""
    __slots__ = ("mistake_id", "module", "mistake_type", "severity",
                 "description", "context", "timestamp", "resolved")

    def __init__(self, module: str, mistake_type: str, severity: str = "medium",
                 description: str = "", context: Optional[Dict] = None) -> None:
        self.mistake_id: str = f"mist_{uuid.uuid4().hex[:8]}"
        self.module: str = module
        self.mistake_type: str = mistake_type
        self.severity: str = severity
        self.description: str = description
        self.context: Dict[str, Any] = context or {}
        self.timestamp: float = time.time()
        self.resolved: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {s: getattr(self, s) for s in self.__slots__}


class StrategyVersion:
    """A versioned strategy snapshot."""
    __slots__ = ("version_id", "version", "changes", "performance_score",
                 "rollback_available", "config_snapshot", "created_at")

    def __init__(self, version: str, changes: str = "",
                 performance_score: float = 0.0,
                 config_snapshot: Optional[Dict] = None) -> None:
        self.version_id: str = f"sv_{uuid.uuid4().hex[:8]}"
        self.version: str = version
        self.changes: str = changes
        self.performance_score: float = performance_score
        self.rollback_available: bool = True
        self.config_snapshot: Dict[str, Any] = config_snapshot or {}
        self.created_at: float = time.time()

    def to_dict(self) -> Dict[str, Any]:
        return {s: getattr(self, s) for s in self.__slots__}


class LearnedPattern:
    """A pattern learned from data analysis."""
    __slots__ = ("pattern_id", "pattern_name", "description", "confidence",
                 "source", "status", "support_count", "created_at")

    def __init__(self, pattern_name: str, description: str = "",
                 confidence: float = 0.5, source: str = "",
                 support_count: int = 1) -> None:
        self.pattern_id: str = f"lp_{uuid.uuid4().hex[:8]}"
        self.pattern_name: str = pattern_name
        self.description: str = description
        self.confidence: float = min(max(confidence, 0.0), 1.0)
        self.source: str = source
        self.status: str = "active"
        self.support_count: int = support_count
        self.created_at: float = time.time()

    def to_dict(self) -> Dict[str, Any]:
        return {s: getattr(self, s) for s in self.__slots__}


class Recommendation:
    """A recommendation generated by the engine."""
    __slots__ = ("recommendation_id", "title", "description", "category",
                 "priority", "expected_impact", "status", "created_at",
                 "implemented_at")

    def __init__(self, title: str, description: str = "",
                 category: str = "general", priority: str = "medium",
                 expected_impact: str = "low") -> None:
        self.recommendation_id: str = f"rec_{uuid.uuid4().hex[:8]}"
        self.title: str = title
        self.description: str = description
        self.category: str = category
        self.priority: str = priority
        self.expected_impact: str = expected_impact
        self.status: str = "pending"
        self.created_at: float = time.time()
        self.implemented_at: Optional[float] = None

    def to_dict(self) -> Dict[str, Any]:
        return {s: getattr(self, s) for s in self.__slots__}


class ImprovementAction:
    """A self-improvement action taken."""
    __slots__ = ("action_id", "action_type", "target_module", "description",
                 "status", "result", "timestamp")

    def __init__(self, action_type: str, target_module: str = "",
                 description: str = "") -> None:
        self.action_id: str = f"imp_{uuid.uuid4().hex[:8]}"
        self.action_type: str = action_type
        self.target_module: str = target_module
        self.description: str = description
        self.status: str = "pending"
        self.result: Dict[str, Any] = {}
        self.timestamp: float = time.time()

    def to_dict(self) -> Dict[str, Any]:
        return {s: getattr(self, s) for s in self.__slots__}


class KnowledgeEntry:
    """An entry in the internal knowledge base."""
    __slots__ = ("entry_id", "topic", "content", "source", "confidence",
                 "tags", "created_at", "updated_at")

    def __init__(self, topic: str, content: str, source: str = "",
                 confidence: float = 0.5, tags: Optional[List[str]] = None) -> None:
        self.entry_id: str = f"ke_{uuid.uuid4().hex[:8]}"
        self.topic: str = topic
        self.content: str = content
        self.source: str = source
        self.confidence: float = confidence
        self.tags: List[str] = tags or []
        self.created_at: float = time.time()
        self.updated_at: float = time.time()

    def to_dict(self) -> Dict[str, Any]:
        return {s: getattr(self, s) for s in self.__slots__}


class DecisionResult:
    """Result of an AI decision."""
    __slots__ = ("decision_id", "question", "decision", "confidence",
                 "reasoning", "context", "timestamp")

    def __init__(self, question: str, decision: str, confidence: float = 0.5,
                 reasoning: str = "", context: Optional[Dict] = None) -> None:
        self.decision_id: str = f"dec_{uuid.uuid4().hex[:8]}"
        self.question: str = question
        self.decision: str = decision
        self.confidence: float = confidence
        self.reasoning: str = reasoning
        self.context: Dict[str, Any] = context or {}
        self.timestamp: float = time.time()

    def to_dict(self) -> Dict[str, Any]:
        return {s: getattr(self, s) for s in self.__slots__}


class PromptTemplate:
    """An optimized prompt template."""
    __slots__ = ("prompt_id", "name", "category", "template", "version",
                 "performance_score", "use_count", "created_at")

    def __init__(self, name: str, category: str, template: str,
                 version: str = "1.0") -> None:
        self.prompt_id: str = f"pt_{uuid.uuid4().hex[:8]}"
        self.name: str = name
        self.category: str = category
        self.template: str = template
        self.version: str = version
        self.performance_score: float = 0.0
        self.use_count: int = 0
        self.created_at: float = time.time()

    def to_dict(self) -> Dict[str, Any]:
        return {s: getattr(self, s) for s in self.__slots__}


class MemoryRecord:
    """A record stored in universal memory."""
    __slots__ = ("memory_id", "key", "value", "namespace", "ttl",
                 "importance", "created_at")

    def __init__(self, key: str, value: Any, namespace: str = "default",
                 ttl: Optional[float] = None, importance: float = 0.5) -> None:
        self.memory_id: str = f"mem_{uuid.uuid4().hex[:8]}"
        self.key: str = key
        self.value: Any = value
        self.namespace: str = namespace
        self.ttl: Optional[float] = ttl
        self.importance: float = importance
        self.created_at: float = time.time()

    def to_dict(self) -> Dict[str, Any]:
        return {s: getattr(self, s) for s in self.__slots__}


class LearningSummary:
    """Summary of learning status."""
    __slots__ = ("total_events", "total_patterns", "total_mistakes",
                 "total_recommendations", "improvements_made",
                 "current_version", "avg_performance_score")

    def __init__(self) -> None:
        self.total_events: int = 0
        self.total_patterns: int = 0
        self.total_mistakes: int = 0
        self.total_recommendations: int = 0
        self.improvements_made: int = 0
        self.current_version: str = "1.0.0"
        self.avg_performance_score: float = 0.0
