"""PromptTemplate — A single prompt template with style, platform, and performance tracking.

Each template is a building block that can be:
- Generated by the Variation Engine
- Tracked by Performance Tracker
- Evolved by Evolution Engine
- Stored in Template Memory
"""
from __future__ import annotations
import time
import uuid
from typing import Any, Dict, List, Optional


_HOOK_TYPES = (
    "question", "statistic", "story", "bold_claim",
    "how_to", "list", "comparison", "controversial",
    "curiosity_gap", "testimonial",
)

_CTA_TYPES = (
    "ask_question", "share_opinion", "save_post", "follow",
    "comment", "link_bio", "dm_me", "tag_friend",
    "swipe_up", "learn_more",
)


class PromptTemplate:
    """A prompt template with full metadata and performance tracking."""

    __slots__ = (
        "template_id", "topic", "platform", "tone", "style",
        "hook_type", "cta_type", "body_template", "hook_template",
        "cta_template", "hashtags_template", "image_prompt_template",
        "tags", "parent_id", "generation", "created_at",
        "last_used_at", "total_uses", "total_impressions",
        "total_engagements", "total_clicks", "engagement_rate",
        "click_rate", "score", "metadata",
    )

    def __init__(
        self,
        topic: str = "",
        platform: str = "facebook",
        tone: str = "professional",
        style: str = "educational",
        hook_type: str = "question",
        cta_type: str = "ask_question",
    ) -> None:
        self.template_id: str = f"tpl_{uuid.uuid4().hex[:12]}"
        self.topic: str = topic
        self.platform: str = platform
        self.tone: str = tone
        self.style: str = style
        self.hook_type: str = hook_type if hook_type in _HOOK_TYPES else "question"
        self.cta_type: str = cta_type if cta_type in _CTA_TYPES else "ask_question"
        self.body_template: str = ""
        self.hook_template: str = ""
        self.cta_template: str = ""
        self.hashtags_template: str = ""
        self.image_prompt_template: str = ""
        self.tags: List[str] = []
        self.parent_id: Optional[str] = None
        self.generation: int = 1
        self.created_at: float = time.time()
        self.last_used_at: Optional[float] = None
        self.total_uses: int = 0
        self.total_impressions: int = 0
        self.total_engagements: int = 0
        self.total_clicks: int = 0
        self.engagement_rate: float = 0.0
        self.click_rate: float = 0.0
        self.score: float = 0.0
        self.metadata: Dict[str, Any] = {}

    @property
    def is_champion(self) -> bool:
        """Is this template the best performer in its category?"""
        return self.score >= 8.0

    @property
    def is_challenger(self) -> bool:
        """Is this template being tested against the champion?"""
        return 5.0 <= self.score < 8.0

    @property
    def is_retired(self) -> bool:
        """Should this template be retired?"""
        return self.total_uses >= 10 and self.score < 3.0

    def record_use(self, impressions: int = 0, engagements: int = 0,
                   clicks: int = 0) -> None:
        """Record a usage event."""
        self.total_uses += 1
        self.total_impressions += impressions
        self.total_engagements += engagements
        self.total_clicks += clicks
        self.last_used_at = time.time()
        self._recalculate_score()

    def _recalculate_score(self) -> None:
        """Recalculate template score based on cumulative performance."""
        if self.total_impressions == 0:
            self.score = 0.0
            self.engagement_rate = 0.0
            self.click_rate = 0.0
            return
        self.engagement_rate = self.total_engagements / self.total_impressions
        self.click_rate = self.total_clicks / self.total_impressions
        # Score: 0-10 scale based on engagement + clicks + consistency
        base = (self.engagement_rate * 60 + self.click_rate * 40)
        consistency_bonus = min(2.0, self.total_uses * 0.1)
        self.score = min(10.0, base + consistency_bonus)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "template_id": self.template_id,
            "topic": self.topic, "platform": self.platform,
            "tone": self.tone, "style": self.style,
            "hook_type": self.hook_type, "cta_type": self.cta_type,
            "body_template": self.body_template,
            "hook_template": self.hook_template,
            "cta_template": self.cta_template,
            "hashtags_template": self.hashtags_template,
            "tags": self.tags, "parent_id": self.parent_id,
            "generation": self.generation,
            "total_uses": self.total_uses,
            "total_impressions": self.total_impressions,
            "total_engagements": self.total_engagements,
            "total_clicks": self.total_clicks,
            "engagement_rate": round(self.engagement_rate, 4),
            "click_rate": round(self.click_rate, 4),
            "score": round(self.score, 2),
            "is_champion": self.is_champion,
            "is_challenger": self.is_challenger,
            "is_retired": self.is_retired,
        }

    def clone(self) -> PromptTemplate:
        """Create a copy of this template for variation."""
        new = PromptTemplate(
            topic=self.topic, platform=self.platform,
            tone=self.tone, style=self.style,
            hook_type=self.hook_type, cta_type=self.cta_type,
        )
        new.body_template = self.body_template
        new.hook_template = self.hook_template
        new.cta_template = self.cta_template
        new.hashtags_template = self.hashtags_template
        new.image_prompt_template = self.image_prompt_template
        new.tags = list(self.tags)
        new.parent_id = self.template_id
        new.generation = self.generation + 1
        new.metadata = dict(self.metadata)
        return new
