"""AtoZ Product Hub integration adapter for UCOS Layer 23.

The repositories remain separate. This adapter exposes only the documented
AIOS.Job.Request transport surface and calls real Layer 23 operations.
"""

from __future__ import annotations

import uuid
from typing import Any

from layers.layer23_website_manager import get_website

SUPPORTED_JOB_TYPES = {
    "content",
    "seo_metadata",
    "pinterest_assets",
    "analytics_insights",
}


def _uuid(value: Any, field: str) -> str:
    try:
        return str(uuid.UUID(str(value)))
    except (ValueError, AttributeError, TypeError) as exc:
        raise ValueError(f"{field} must be a valid UUID") from exc


def dispatch_job(data: dict[str, Any]) -> dict[str, Any]:
    """Dispatch an AIOS job into Layer 23 using real data only."""
    request_id = _uuid(data.get("request_id"), "request_id")
    niche_id = _uuid(data.get("niche_id"), "niche_id")
    job_type = str(data.get("job_type") or "").strip()
    if job_type not in SUPPORTED_JOB_TYPES:
        raise ValueError(f"unsupported job_type: {job_type}")

    context = data.get("context")
    if not isinstance(context, dict):
        raise ValueError("context must be an object")

    site = get_website(
        domain=str(context.get("domain") or "example.com"),
        site_name=str(context.get("site_name") or "AtozProductHub"),
    )
    job_id = str(uuid.uuid4())

    if job_type == "content":
        title = str(context.get("title") or "").strip()
        body = str(context.get("content") or "").strip()
        if not title or not body:
            raise ValueError("content jobs require real context.title and context.content")
        article = site.create_article(
            title=title,
            content=body,
            category=str(context.get("category") or ""),
            tags=list(context.get("tags") or []),
            author=str(context.get("author") or "AtozProductHub"),
            featured_image=str(context.get("featured_image") or ""),
            meta_title=str(context.get("meta_title") or ""),
            meta_description=str(context.get("meta_description") or ""),
            status="published" if bool(context.get("publish")) else "draft",
        )
        return {
            "job_id": job_id,
            "request_id": request_id,
            "niche_id": niche_id,
            "state": "succeeded",
            "result_ref": f"layer23:article:{article.article_id}",
            "result": article.to_dict(),
        }

    if job_type == "seo_metadata":
        article_id = str(context.get("article_id") or "").strip()
        if not article_id:
            raise ValueError("seo_metadata jobs require context.article_id")
        metadata = site.generate_article_seo(article_id)
        if metadata is None:
            raise LookupError(f"article not found: {article_id}")
        return {
            "job_id": job_id,
            "request_id": request_id,
            "niche_id": niche_id,
            "state": "succeeded",
            "result_ref": f"layer23:seo:{article_id}",
            "result": metadata.to_dict(),
        }

    if job_type == "analytics_insights":
        return {
            "job_id": job_id,
            "request_id": request_id,
            "niche_id": niche_id,
            "state": "succeeded",
            "result_ref": "layer23:website:status",
            "result": site.get_status(),
        }

    raise NotImplementedError(
        "pinterest_assets is not generated by Layer 23; the AI OS must provide approved assets"
    )
